// src/theme/ProjectNotices.tsx
import React from 'react';
import Admonition from '@theme/Admonition';
import useDocusaurusContext from '@docusaurus/useDocusaurusContext';
import { getItemNotices, type NoticeType } from './notices';

interface ProjectNoticesProps {
  item: string;
}

const noticeTypeToAdmonition: Record<NoticeType, string> = {
  info: 'tip',
  warning: 'caution',
  danger: 'danger',
};

export default function ProjectNotices({
  item,
}: ProjectNoticesProps): JSX.Element | null {
  const {
    i18n: { currentLocale },
  } = useDocusaurusContext();
  const notices = getItemNotices(currentLocale, item);

  if (notices.length === 0) return null;

  return (
    <div className="project-notices">
      {notices.map((n, idx) => (
        <Admonition
          key={idx}
          type={noticeTypeToAdmonition[n.type] as 'tip' | 'caution' | 'danger'}
          title={n.title}
        >
          {n.lines.map((line, li) => (
            <p key={li} dangerouslySetInnerHTML={{ __html: line }} />
          ))}
        </Admonition>
      ))}
    </div>
  );
}

// docs/.vitepress/theme/components/ProjectNotices.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useData } from 'vitepress'
import { getItemNotices } from '../notices'

interface Props {
  item: string
}

const props = defineProps<Props>()
const { lang } = useData()

const notices = computed(() => getItemNotices(lang.value, props.item))
</script>

<template>
  <div v-if="notices.length" class="project-notices">
    <div
      v-for="(n, idx) in notices"
      :key="idx"
      class="custom-block"
      :class="n.type === 'info' ? 'tip' : n.type"
    >
      <p class="custom-block-title">{{ n.title }}</p>
      <p v-for="(line, li) in n.lines" :key="li" v-html="line"></p>
    </div>
  </div>
</template>

<style>
.project-notices {
  margin: 16px 0;
}

.project-notices .custom-block + .custom-block {
  margin-top: 10px;
}
</style>
